const Classes = [
    {
        "id": "1",
        "title": "Algebra II",
        "subtitle": "Period 3",
        "theme": "bg-indigo-500",
        "coverImage": null,
        "teacher": { "name": "Ms. Patel", "avatar": null, "initials": "MP" },
        "unreadCount": 0,
        "deadline": null,
        "memberCount": 24,
        "onlineCount": 3,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "2",
        "title": "World History",
        "subtitle": "Period 1",
        "theme": "bg-rose-500",
        "coverImage": null,
        "teacher": { "name": "Mr. Davis", "avatar": null, "initials": "MD" },
        "unreadCount": 2,
        "deadline": "2026-09-02T23:59:00Z",
        "memberCount": 28,
        "onlineCount": 5,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "3",
        "title": "AP Physics",
        "subtitle": "Period 4",
        "theme": "bg-blue-600",
        "coverImage": "https://example.com/physics-bg.jpg",
        "teacher": { "name": "Dr. Chen", "avatar": null, "initials": "LC" },
        "unreadCount": 5,
        "deadline": "2026-08-30T17:00:00Z",
        "memberCount": 18,
        "onlineCount": 12,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "4",
        "title": "English Literature",
        "subtitle": "Period 2",
        "theme": "bg-emerald-600",
        "coverImage": null,
        "teacher": { "name": "Mrs. Smith", "avatar": "https://example.com/smith.jpg", "initials": "SS" },
        "unreadCount": 0,
        "deadline": null,
        "memberCount": 30,
        "onlineCount": 1,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "5",
        "title": "Physical Education",
        "subtitle": "Period 6",
        "theme": "bg-orange-500",
        "coverImage": null,
        "teacher": { "name": "Coach Johnson", "avatar": null, "initials": "CJ" },
        "unreadCount": 0,
        "deadline": null,
        "memberCount": 45,
        "onlineCount": 0,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "6",
        "title": "Chemistry Honors",
        "subtitle": "Period 5",
        "theme": "bg-cyan-600",
        "coverImage": null,
        "teacher": { "name": "Mr. White", "avatar": null, "initials": "MW" },
        "unreadCount": 12,
        "deadline": "2026-09-05T08:00:00Z",
        "memberCount": 22,
        "onlineCount": 8,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "7",
        "title": "Spanish II",
        "subtitle": "Period 7",
        "theme": "bg-yellow-500",
        "coverImage": null,
        "teacher": { "name": "Sra. Garcia", "avatar": null, "initials": "EG" },
        "unreadCount": 1,
        "deadline": null,
        "memberCount": 26,
        "onlineCount": 4,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "8",
        "title": "Computer Science",
        "subtitle": "Period 8",
        "theme": "bg-slate-700",
        "coverImage": null,
        "teacher": { "name": "Ms. Turing", "avatar": null, "initials": "AT" },
        "unreadCount": 0,
        "deadline": "2026-09-01T23:59:00Z",
        "memberCount": 20,
        "onlineCount": 18,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "9",
        "title": "Art Fundamentals",
        "subtitle": "Period 1",
        "theme": "bg-pink-500",
        "coverImage": "https://example.com/art-bg.jpg",
        "teacher": { "name": "Mr. Ross", "avatar": null, "initials": "BR" },
        "unreadCount": 0,
        "deadline": null,
        "memberCount": 32,
        "onlineCount": 2,
        "onAction": null,
        "onOpen": null
    },
    {
        "id": "10",
        "title": "Symphony Orchestra",
        "subtitle": "Period 2",
        "theme": "bg-purple-600",
        "coverImage": null,
        "teacher": { "name": "Ms. Melody", "avatar": null, "initials": "MM" },
        "unreadCount": 4,
        "deadline": "2026-09-10T15:30:00Z",
        "memberCount": 55,
        "onlineCount": 0,
        "onAction": null,
        "onOpen": null
    }
];

export default Classes;