import { useState } from "react";
import { ACTIVE_NOW, QUICK_LINKS } from "../data/classPageData.js";
import { ClassroomAvatar } from "./ClassroomAvatar.jsx";
import { ClassroomIcon } from "./ClassroomIcon.jsx";

export default function ClassSidePanel({ teacher = false, upcoming = [] }) {
  const [links, setLinks] = useState(QUICK_LINKS);
  const [adding, setAdding] = useState(false);
  const [form, setForm] = useState({ label: "", href: "" });
  const addLink = (event) => { event.preventDefault(); if (!form.label.trim() || !form.href.trim()) return; setLinks((items) => [...items, { id: Date.now(), icon: "link", ...form }]); setForm({ label: "", href: "" }); setAdding(false); };
  const online = ACTIVE_NOW.slice(0, 5);
  return <div className="space-y-4"><Panel title="Upcoming (next 7 days)">{upcoming.length ? <ul className="space-y-2.5">{upcoming.map((item) => <li key={item.id} className="flex items-start gap-2.5"><ClassroomIcon name="clock" className="mt-0.5 h-4 w-4 shrink-0 text-secondary" /><div><p className="text-sm text-text-main">{item.title}</p><p className="text-xs text-text-muted">{item.dueDate}</p></div></li>)}</ul> : <p className="text-sm text-text-muted">Nothing due in the next 7 days</p>}</Panel><Panel title="Active now" dot>{online.length ? <ul className="space-y-2.5">{online.map((person) => <li key={person.id} className="flex items-center gap-2.5"><div className="relative"><ClassroomAvatar name={person.name} size="h-7 w-7" /><span className="absolute -bottom-0.5 -right-0.5 h-2.5 w-2.5 rounded-full border-2 border-surface bg-success" /></div><span className="text-sm text-text-main">{person.name}</span></li>)}{ACTIVE_NOW.length > online.length && <li className="text-xs text-text-muted">+{ACTIVE_NOW.length - online.length} more</li>}</ul> : <p className="text-sm text-text-muted">No one else is online right now.</p>}</Panel><Panel title="Quick links">{links.length ? <ul className="space-y-1">{links.map((link) => <li key={link.id}><a href={link.href || "#"} target={link.href?.startsWith("http") ? "_blank" : undefined} rel={link.href?.startsWith("http") ? "noreferrer" : undefined} className="flex items-center gap-2.5 rounded-lg px-2 py-2 text-sm text-text-main hover:bg-canvas"><ClassroomIcon name={link.icon} className="h-4 w-4 text-text-muted" />{link.label}</a></li>)}</ul> : <p className="text-sm text-text-muted">No quick links yet.</p>}{teacher && (adding ? <form onSubmit={addLink} className="mt-3 space-y-2"><input value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} placeholder="Link label" className="w-full rounded-lg border border-border bg-canvas px-2 py-1.5 text-sm" /><input value={form.href} onChange={(e) => setForm({ ...form, href: e.target.value })} placeholder="https://…" className="w-full rounded-lg border border-border bg-canvas px-2 py-1.5 text-sm" /><button className="text-sm font-medium text-primary">Save link</button></form> : <button onClick={() => setAdding(true)} className="mt-2 rounded-lg px-2 py-1 text-sm font-medium text-primary hover:bg-canvas">+ Add link</button>)}</Panel></div>;
}
function Panel({ title, children, dot }) { return <div className="rounded-2xl bg-surface p-4 shadow-sm ring-1 ring-border"><h3 className="mb-3 flex items-center gap-1.5 text-sm font-semibold text-text-heading">{dot && <span className="h-2 w-2 rounded-full bg-success" />}{title}</h3>{children}</div>; }
